stages:
  - prepare
  - package

generate-package-pipeline:
  stage: prepare
  image: akamai/jsonnet
  script:
    - |-
      jsonnet -S \
        --ext-str "branch=${CI_COMMIT_BRANCH:-}" \
        --ext-str "target=" \
        .gitlab/ci/package-pipeline.jsonnet \
        > package-pipeline.yaml
  artifacts:
    paths:
      - package-pipeline.yaml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.+$/'
    - when: never

run-package-pipeline:
  stage: package
  trigger:
    include:
      - artifact: package-pipeline.yaml
        job: generate-package-pipeline
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH =~ /^feature\/.+$/'
    - when: never
