name: haproxy-inspect

services:
  haproxy:
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        ALPINE_CURL_VERSION: ${ALPINE_CURL_VERSION}
        HAPROXY_VERSION: ${HAPROXY_VERSION}
        UBI9_MICRO_VERSION: ${UBI9_MICRO_VERSION}
    container_name: haproxy-inspect-container
    entrypoint:
      - /usr/local/haproxy/sbin/haproxy
    command:
      - -vv
