name: nginx-inspect

services:
  nginx:
    platform: linux/amd64
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        ALPINE_CURL_VERSION: ${ALPINE_CURL_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
        NGINX_MODULE_VTS_VERSION: ${NGINX_MODULE_VTS_VERSION}
        UBI9_MICRO_VERSION: ${UBI9_MICRO_VERSION}
    container_name: nginx-inspect-container
    entrypoint:
      - /usr/local/nginx/sbin/nginx
    command:
      - -V
