worker_processes 1;
error_log stderr notice;
events {}
http {
    js_engine qjs;
    js_import scripting from scripting.js;
    server {
        listen 127.0.0.1:18081;
        location = /njs {
            js_content scripting.version;
        }
    }
}
stream {
    js_engine qjs;
    js_import scripting from scripting.js;
    js_set $greeting scripting.greeting;
    server {
        listen 127.0.0.1:18082;
        return $greeting;
    }
}
