name: Build Package

on:
  workflow_dispatch:
    inputs:
      target:
        description: Build target
        required: true
        type: choice
        options:
          - nginx
          - haproxy
          - apache-httpd
          - coredns
          - dnsmasq
          - vector
          - monit

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.metadata.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve package tag
        id: metadata
        env:
          TARGET: ${{ inputs.target }}
        run: |-
          TAG_PREFIX="$(sh scripts/metadata.sh get-tag-prefix "$TARGET")"
          VERSION="$(sh scripts/metadata.sh get-official-version "$TARGET")"
          echo "tag=${TAG_PREFIX}-${VERSION}.0" >> "$GITHUB_OUTPUT"

  build:
    needs: resolve
    permissions:
      contents: write
      security-events: write
    uses: ./.github/workflows/template-release.yaml
    with:
      target: ${{ inputs.target }}
      tag: ${{ needs.resolve.outputs.tag }}
      upload_release: false
